almacenzonainventario_index:
    path:     /
    defaults: { _controller: "AppBundle:AlmacenZonaInventario:index" }
    methods:  [GET, POST]

almacenzonainventario_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:AlmacenZonaInventario:show" }
    methods:  GET

almacenzonainventario_new:
    path:     /{id}/new
    defaults: { _controller: "AppBundle:AlmacenZonaInventario:new" }
    methods:  [GET, POST]

almacenzonainventario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:AlmacenZonaInventario:edit" }
    methods:  [GET, POST]

almacenzonainventario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:AlmacenZonaInventario:delete" }
    methods:  DELETE

almacenzonainventario_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:AlmacenZonaInventario:erase" }
    methods:  GET
