equipotrabajo_index:
    path:     /
    defaults: { _controller: "AppBundle:EquipoTrabajo:index" }
    methods:  [GET, POST]

equipotrabajo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:EquipoTrabajo:show" }
    methods:  GET

equipotrabajo_new:
    path:     /new
    defaults: { _controller: "AppBundle:EquipoTrabajo:new" }
    methods:  [GET, POST]

equipotrabajo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:EquipoTrabajo:edit" }
    methods:  [GET, POST]

equipotrabajo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:EquipoTrabajo:delete" }
    methods:  DELETE

equipotrabajo_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:EquipoTrabajo:erase" }
    methods:  GET
