inventarioordennovedad_index:
    path:     /
    defaults: { _controller: "AppBundle:InventarioOrdenNovedad:index" }
    methods:  [GET, POST]

inventarioordennovedad_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:InventarioOrdenNovedad:show" }
    methods:  GET

inventarioordennovedad_new:
    path:     /new
    defaults: { _controller: "AppBundle:InventarioOrdenNovedad:new" }
    methods:  [GET, POST]

inventarioordennovedad_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:InventarioOrdenNovedad:edit" }
    methods:  [GET, POST]

inventarioordennovedad_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:InventarioOrdenNovedad:delete" }
    methods:  DELETE

inventarioordennovedad_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:InventarioOrdenNovedad:erase" }
    methods:  GET
