materialmedida_index:
    path:     /
    defaults: { _controller: "AppBundle:MaterialMedida:index" }
    methods:  [GET, POST]

materialmedida_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:MaterialMedida:show" }
    methods:  GET

materialmedida_new:
    path:     /new
    defaults: { _controller: "AppBundle:MaterialMedida:new" }
    methods:  [GET, POST]

materialmedida_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:MaterialMedida:edit" }
    methods:  [GET, POST]

materialmedida_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:MaterialMedida:delete" }
    methods:  DELETE

materialmedida_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:MaterialMedida:erase" }
    methods:  GET
