procesoencargado_index:
    path:     /
    defaults: { _controller: "AppBundle:ProcesoEncargado:index" }
    methods:  [GET, POST]

procesoencargado_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProcesoEncargado:show" }
    methods:  GET

procesoencargado_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProcesoEncargado:new" }
    methods:  [GET, POST]

procesoencargado_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProcesoEncargado:edit" }
    methods:  [GET, POST]

procesoencargado_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProcesoEncargado:delete" }
    methods:  DELETE

procesoencargado_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProcesoEncargado:erase" }
    methods:  GET

procesoencargado_terminar_trabajo:
    path:     /{procesoEncargado}/proceso_encargado/{diseno}/diseno/terminar_trabajo
    defaults: { _controller: "AppBundle:ProcesoEncargado:terminar_trabajo" }
    methods:  GET
