procesonombre_index:
    path:     /
    defaults: { _controller: "AppBundle:ProcesoNombre:index" }
    methods:  [GET, POST]

procesonombre_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProcesoNombre:show" }
    methods:  GET

procesonombre_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProcesoNombre:new" }
    methods:  [GET, POST]

procesonombre_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProcesoNombre:edit" }
    methods:  [GET, POST]

procesonombre_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProcesoNombre:delete" }
    methods:  DELETE

procesonombre_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProcesoNombre:erase" }
    methods:  GET
