procesonotas_index:
    path:     /
    defaults: { _controller: "AppBundle:ProcesoNotas:index" }
    methods:  [GET, POST]

procesonotas_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProcesoNotas:show" }
    methods:  GET

procesonotas_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProcesoNotas:new" }
    methods:  [GET, POST]

procesonotas_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProcesoNotas:edit" }
    methods:  [GET, POST]

procesonotas_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProcesoNotas:delete" }
    methods:  DELETE

procesonotas_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProcesoNotas:erase" }
    methods:  GET
