produccion_index:
    path:     /
    defaults: { _controller: "AppBundle:Produccion:index" }
    methods:  GET

produccion_preliquidar:
    path:     /
    defaults: { _controller: "AppBundle:Produccion:preliquidar" }
    methods:  POST

default_newordendiseno:
    path:     /newordendiseno
    defaults: { _controller: "AppBundle:Produccion:newOrdenDiseno" }
    methods:  POST

#default_servicios:
#    path:     /servicios
#    defaults: { _controller: "AppBundle:Default:servicios" }
#    methods:  GET
#
#default_empresa:
#    path:     /empresa
#    defaults: { _controller: "AppBundle:Default:empresa" }
#    methods:  GET
#
#default_grafica:
#    path:     /grafica
#    defaults: { _controller: "AppBundle:Default:grafica" }
#    methods:  GET
#
#default_contactanos:
#    path:     /contactanos
#    defaults: { _controller: "AppBundle:Default:contactanos" }
#    methods:  [GET, POST]

#default_test_email:
#    path:     /test_email
#    defaults: { _controller: "AppBundle:Default:testEmail" }
#    methods:  [GET, POST]
