productocomplemento_index:
    path:     /
    defaults: { _controller: "AppBundle:ProductoComplemento:index" }
    methods:  [GET, POST]

productocomplemento_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProductoComplemento:show" }
    methods:  GET

productocomplemento_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProductoComplemento:new" }
    methods:  [GET, POST]

productocomplemento_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProductoComplemento:edit" }
    methods:  [GET, POST]

productocomplemento_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProductoComplemento:delete" }
    methods:  DELETE

productocomplemento_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProductoComplemento:erase" }
    methods:  GET
