productotalla_index:
    path:     /
    defaults: { _controller: "AppBundle:ProductoTalla:index" }
    methods:  [GET, POST]

productotalla_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProductoTalla:show" }
    methods:  GET

productotalla_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProductoTalla:new" }
    methods:  [GET, POST]

productotalla_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProductoTalla:edit" }
    methods:  [GET, POST]

productotalla_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProductoTalla:delete" }
    methods:  DELETE

productotalla_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProductoTalla:erase" }
    methods:  GET
