productodescripcion_index:
    path:     /
    defaults: { _controller: "AppBundle:ProductoDescripcion:index" }
    methods:  [GET, POST]

productodescripcion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProductoDescripcion:show" }
    methods:  GET

productodescripcion_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProductoDescripcion:new" }
    methods:  [GET, POST]

productodescripcion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProductoDescripcion:edit" }
    methods:  [GET, POST]

productodescripcion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProductoDescripcion:delete" }
    methods:  DELETE

productodescripcion_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProductoDescripcion:erase" }
    methods:  GET
