productocategoria_index:
    path:     /
    defaults: { _controller: "AppBundle:ProductoCategoria:index" }
    methods:  [GET, POST]

productocategoria_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ProductoCategoria:show" }
    methods:  GET

productocategoria_new:
    path:     /new
    defaults: { _controller: "AppBundle:ProductoCategoria:new" }
    methods:  [GET, POST]

productocategoria_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ProductoCategoria:edit" }
    methods:  [GET, POST]

productocategoria_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ProductoCategoria:delete" }
    methods:  DELETE

productocategoria_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:ProductoCategoria:erase" }
    methods:  GET
