proveedor_index:
    path:     /
    defaults: { _controller: "AppBundle:Proveedor:index" }
    methods:  [GET, POST]

proveedor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Proveedor:show" }
    methods:  GET

proveedor_new:
    path:     /new
    defaults: { _controller: "AppBundle:Proveedor:new" }
    methods:  [GET, POST]

proveedor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Proveedor:edit" }
    methods:  [GET, POST]

proveedor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Proveedor:delete" }
    methods:  DELETE

proveedor_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:Proveedor:erase" }
    methods:  GET
