storeinicio_index:
    path:     /
    defaults: { _controller: "AppBundle:StoreInicio:index" }
    methods:  [GET, POST]

storeinicio_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:StoreInicio:show" }
    methods:  GET

storeinicio_new:
    path:     /new
    defaults: { _controller: "AppBundle:StoreInicio:new" }
    methods:  [GET, POST]

storeinicio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:StoreInicio:edit" }
    methods:  [GET, POST]

storeinicio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:StoreInicio:delete" }
    methods:  DELETE

storeinicio_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:StoreInicio:erase" }
    methods:  GET
