storeseo_index:
    path:     /
    defaults: { _controller: "AppBundle:StoreSeo:index" }
    methods:  [GET, POST]

storeseo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:StoreSeo:show" }
    methods:  GET

storeseo_new:
    path:     /new
    defaults: { _controller: "AppBundle:StoreSeo:new" }
    methods:  [GET, POST]

storeseo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:StoreSeo:edit" }
    methods:  [GET, POST]

storeseo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:StoreSeo:delete" }
    methods:  DELETE

storeseo_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:StoreSeo:erase" }
    methods:  GET
