storebonos_index:
    path:     /
    defaults: { _controller: "AppBundle:StoreBonos:index" }
    methods:  [GET, POST]

storebonos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:StoreBonos:show" }
    methods:  GET

storebonos_new:
    path:     /new
    defaults: { _controller: "AppBundle:StoreBonos:new" }
    methods:  [GET, POST]

storebonos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:StoreBonos:edit" }
    methods:  [GET, POST]

storebonos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:StoreBonos:delete" }
    methods:  DELETE

storebonos_erase:
    path:     /{id}/erase
    defaults: { _controller: "AppBundle:StoreBonos:erase" }
    methods:  GET
