AppBundle\Entity\Almacen:
    type: entity
    table: almacen
    indexes:
        pais:
            columns:
                - pais
        estado:
            columns:
                - estado
        usuario_creacion:
            columns:
                - usuario_creacion
        ciudad:
            columns:
                - ciudad
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
        telefono1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        telefono2:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nombreContacto:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
            column: nombre_contacto
        telefonoContacto:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: telefono_contacto
        fechaCreacion:
            type: datetime
            nullable: false
            column: fecha_creacion
        estado:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
    oneToMany:
        zonas:
            targetEntity: AlmacenZona
            mappedBy: almacen
    manyToOne:
        ciudad:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciudad:
                    referencedColumnName: id
            orphanRemoval: false
        pais:
            targetEntity: Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                pais:
                    referencedColumnName: id
            orphanRemoval: false
        usuarioCreacion:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_creacion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
