AppBundle\Entity\Country:
    type: entity
    table: country
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        currency:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        extra1:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        extra2:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        cities:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            mappedBy: country
            inversedBy: country
    lifecycleCallbacks: {  }
