AppBundle\Entity\DisenoBordado:
    type: entity
    table: diseno_bordado
    indexes:
        fk_bordado_diseno:
            columns:
                - diseno
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cantidad:
            type: integer
            nullable: false
            options:
                unsigned: false
        tipo:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        estado:
            type: integer
            nullable: false
            options:
                unsigned: false
        fechaCreacion:
            type: datetime
            nullable: false
            column: fecha_creacion
    manyToOne:
        diseno:
            targetEntity: Diseno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                diseno:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
