AppBundle\Entity\MaterialCategoria:
    type: entity
    table: material_categoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
    lifecycleCallbacks: {  }
