AppBundle\Entity\OrdenCompraPago:
    type: entity
    table: orden_compra_pago
    indexes:
        usuario_creacion:
            columns:
                - usuario_creacion
        orden_compra:
            columns:
                - orden_compra
        referencia:
            columns:
                - referencia
        estado:
            columns:
                - estado
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaCreacion:
            type: datetime
            nullable: false
            column: fecha_creacion
        tipoPago:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: tipo_pago
        valor:
            type: float
            nullable: false
            precision: 25
            scale: 2
        referencia:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        estado:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
    manyToOne:
        ordenCompra:
            targetEntity: OrdenCompra
            cascade: {  }
            fetch: LAZY
            mappedBy: pagos
            inversedBy: pagos
            joinColumns:
                orden_compra:
                    referencedColumnName: id
            orphanRemoval: false
        usuarioCreacion:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_creacion:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
