AppBundle\Entity\Producto:
    type: entity
    table: producto
    indexes:
        categoria:
            columns:
                - categoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        precioMayorista:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: precio_mayorista
        precioDetal:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: precio_detal
        referencia:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        etiqueta:
            type: string
            nullable: false
            length: 120
            options:
                fixed: false
        marca:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        estado:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    oneToMany: 
        imagenes:
            targetEntity: ProductoImagen
            mappedBy: producto
            cascade:  [persist]
            orphanRemoval: true
        tallas:
            targetEntity: ProductoTalla
            mappedBy: producto
            cascade:  [persist]
        colores:
            targetEntity: ProductoColor
            mappedBy: producto
            cascade:  [persist]
        descripciones:
            targetEntity: ProductoDescripcion
            mappedBy: producto
            cascade:  [persist]
        complementos:
            targetEntity: ProductoComplemento
            mappedBy: producto
            cascade:  [persist]
    manyToOne:
        categoria:
            targetEntity: ProductoCategoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
