AppBundle\Entity\ProduccionOrden:
    type: entity
    table: produccion_orden
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        referencia:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        fechaCreacion:
            type: datetime
            nullable: false
            column: fecha_creacion
        fechaFinalizacion:
            type: datetime
            nullable: true
            column: fecha_finalizacion
        duracion:
            type: integer
            nullable: true
            options:
                unsigned: false
        estado:
            type: integer
            nullable: false
            options:
                unsigned: false
        notas:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
