AppBundle\Entity\ProductoTalla:
    type: entity
    table: producto_talla
    indexes:
        fk_talla_producto:
            columns:
                - producto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    manyToOne:
        producto:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                producto:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
