AppBundle\Entity\ProductoDescripcion:
    type: entity
    table: producto_descripcion
    indexes:
        fk_producto_descripcion:
            columns:
                - producto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texto:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        texto_en:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        producto:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                producto:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
