AppBundle\Entity\StoreTiendaSlider:
    type: entity
    table: store_tienda_slider
    indexes:
        fk_slider_store:
            columns:
                - store
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        imagen:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        orden:
            type: integer
            nullable: false
            options:
                unsigned: false
        fechaModificacion:
            type: datetime
            nullable: false
            column: fecha_modificacion
    manyToOne:
        store:
            targetEntity: StoreTienda
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                store:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
