AppBundle\Entity\TiendaCliente:
    type: entity
    table: tienda_cliente
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        apellido:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        identificacion:
            type: integer
            nullable: false
            options:
                unsigned: false
        email:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        telefono:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
